#!/bin/bash

usage(){
	echo "Usage to build all the samples if your compiler supporting c++11 is named g++:"
	echo "	./buildTests"
	echo ""
	echo "Usage to build all the samples if your compiler supporting c++11 is not named g++:"
	echo "	./buildTests <g++Name>"
	echo ""
	echo "g++Name is the name of the g++ to use (i.e.: g++ or g++-4.7)"
	echo ""
	echo "Note: Must be called from the sample-src directory."
	echo ""
}

if [ "$#" -gt 1 ]
then
	usage
elif [ "$#" == 1 ]
then
	GXX=$1
	for file in $(find * | grep '.cpp')
	do
		echo Building $file
		./Scripts/build.sh $GXX $file
	done
else
	GXX="g++"
	for file in $(find * | grep '.cpp')
	do
		echo Building $file
		./Scripts/build.sh $GXX $file
	done
fi
