/**< All the includes */
#include "NGS/utility/utility.h"
#include "NGS/IO/uToken.h"
#include "NGS/IO/uHeader.h"
#include "NGS/IO/Parser/uParser.h"
#include "NGS/uRegion.h"
#include "NGS/uFormats.h"
#include "NGS/uGeneException.h"
#include "NGS/uTags.h"
#include "NGS/uBasicNGS.h"
#include "NGS/uGene.h"
#include "api/BamReader.h"
#include "api/BamWriter.h"
